"use strict";

var MUSIC_CIRCLE_OFFSET = window.innerWidth / 25;
var PROGRESS_CIRCLE_BORDER = 2;
var PROGRESS_CIRCLE_RADIUS = 8;
var PROGRESS_START_HEIGHT = 24;
var PROGRESS_START_WIDTH = 6;
var DRAG_CONTROL_OFFSET = 6;